version: "{build}"

os: Windows Server 2012
platform:
  - x64

environment:
  matrix:
    - ruby_version: "23-x64"
    - ruby_version: "23"

clone_folder: c:\projects\chefdk
clone_depth: 1
skip_tags: true
branches:
  only:
    - master

install:
  - systeminfo
  - winrm quickconfig -q
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ps: $env:RUBYGEMS_VERSION=$(findstr rubygems omnibus_overrides.rb | %{ $_.split(" ")[3] })
  - echo %PATH%
  - ruby --version
  - gem update --system %RUBYGEMS_VERSION% || gem update --system %RUBYGEMS_VERSION% || gem update --system %RUBYGEMS_VERSION%
  - update_rubygems
  - gem --version
  - bundler --version
  - SET BUNDLE_IGNORE_CONFIG=true
  - SET BUNDLE_FROZEN=1
  - SET BUNDLE_WITHOUT=development:guard:maintenance:tools:integration:changelog:docgen:travis:style:omnibus_package:aix:bsd:linux:mac_os_x:solaris

build_script:
  - bundle install || bundle install || bundle install

test_script:
  - bundle exec rspec
